plugins { id 'com.android.application' }

android {
    namespace 'kz.almasofficial.br'
    compileSdk 35

    defaultConfig {
        applicationId 'kz.almasofficial.br.universal'
        minSdk 23
        targetSdk 35
        versionCode 6
        versionName '0.6.0-bridge'
    }
}

dependencies {
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5'
}
